Backup Current Image

diff --git a/.github/workflows/deploy-ssm.yml b/.github/workflows/deploy-ssm.yml
--- a/.github/workflows/deploy-ssm.yml
+++ b/.github/workflows/deploy-ssm.yml
@@ -91,7 +91,7 @@ jobs:
 
           aws-region: ${{ secrets.AWS_REGION }}
 
-
+          
       ############################################################
       # Execute Bootstrap Through SSM
       ############################################################
@@ -123,7 +123,25 @@ jobs:
 
               "ENV",
 
-              "bash /tmp/bootstrap.sh"
+              "bash /tmp/bootstrap.sh",
+
+              "echo 'Esperando que la aplicación inicie...'",
+
+              "sleep 20",
+
+              "STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:80/health)",
+
+              "echo HTTP_STATUS=$STATUS",
+
+              "if [ \"$STATUS\" != \"200\" ]; then",
+
+              "  echo 'Health Check FAILED'",
+
+              "  exit 100",
+
+              "fi",
+
+              "echo 'Health Check OK'"
 
             ]
           }
@@ -142,9 +160,10 @@ jobs:
           echo "======================================"
           echo "Command ID: ${COMMAND_ID}"
           echo "======================================"
-          echo "Esperando 20 segundos..."
 
-          sleep 20
+          aws ssm wait command-executed \
+            --command-id "${COMMAND_ID}" \
+            --instance-id "${{ steps.tf.outputs.instance_id }}"
 
           echo "======================================"
           echo "Execution Result"
@@ -173,6 +192,19 @@ jobs:
             --instance-id "${{ steps.tf.outputs.instance_id }}" \
             --query StandardErrorContent \
             --output text
+
+          STATUS=$(
+            aws ssm get-command-invocation \
+              --command-id "${COMMAND_ID}" \
+              --instance-id "${{ steps.tf.outputs.instance_id }}" \
+              --query Status \
+              --output text
+          )
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "Deployment failed."
+            exit 1
+          fi
 
 
 
