corrección deploy ssm

diff --git a/.github/workflows/deploy-ssm.yml b/.github/workflows/deploy-ssm.yml
--- a/.github/workflows/deploy-ssm.yml
+++ b/.github/workflows/deploy-ssm.yml
@@ -123,25 +123,7 @@ jobs:
 
               "ENV",
 
-              "bash /tmp/bootstrap.sh",
-
-              "echo 'Esperando que la aplicación inicie...'",
-
-              "sleep 20",
-
-              "STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:80/health)",
-
-              "echo HTTP_STATUS=$STATUS",
-
-              "if [ \"$STATUS\" != \"200\" ]; then",
-
-              "  echo 'Health Check FAILED'",
-
-              "  exit 100",
-
-              "fi",
-
-              "echo 'Health Check OK'"
+              "bash /tmp/bootstrap.sh"
 
             ]
           }
@@ -173,6 +155,8 @@ jobs:
             --command-id "${COMMAND_ID}" \
             --instance-id "${{ steps.tf.outputs.instance_id }}"
 
+            
+
           echo "==============================="
           echo "STDOUT"
           echo "==============================="
@@ -201,11 +185,48 @@ jobs:
               --output text
           )
 
-          if [ "$STATUS" != "Success" ]; then
-            echo "Deployment failed."
+          echo "Deployment Status = ${STATUS}"
+
+          if [ "${STATUS}" != "Success" ]; then
+            echo "Deployment FAILED"
             exit 1
+          fi  
+
+          echo "======================================"
+          echo "Waiting Health Check..."
+          echo "======================================"
+
+          sleep 20
+
+          aws ssm send-command \
+            --instance-ids "${{ steps.tf.outputs.instance_id }}" \
+            --document-name "AWS-RunShellScript" \
+            --parameters 'commands=["curl -fsS http://localhost:80/health"]' \
+            --query Command.CommandId \
+            --output text > health.txt
+
+          HEALTH_COMMAND=$(cat health.txt)
+
+          sleep 10
+
+          HEALTH_STATUS=$(
+            aws ssm get-command-invocation \
+                --command-id "$HEALTH_COMMAND" \
+                --instance-id "${{ steps.tf.outputs.instance_id }}" \
+                --query Status \
+                --output text
+          )
+
+          echo "Health Status = ${HEALTH_STATUS}"
+
+          if [ "${HEALTH_STATUS}" != "Success" ]; then
+              echo "Health Check FAILED"
+              exit 1
           fi
 
+          echo "Health Check OK"
+
+            
 
 
             
